import type { Project } from '../interfaces/project.interface';

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: 'E-Commerce Platform',
    description: 'Una aplicación web moderna construida con React y TypeScript. Incluye características avanzadas de UI/UX, carrito de compras y sistema de autenticación.',
    technologies: ['React', 'TypeScript', 'CSS3'],
    image: '/api/placeholder/400/300',
    link: 'https://example.com',
    github: 'https://github.com/example',
  },
  {
    id: 2,
    title: 'Sistema de Gestión',
    description: 'Sistema de gestión completo con backend robusto y frontend intuitivo. Permite gestionar usuarios, productos y reportes en tiempo real.',
    technologies: ['Node.js', 'React', 'MongoDB'],
    image: '/api/placeholder/400/300',
    link: 'https://example.com',
    github: 'https://github.com/example',
  },
  {
    id: 3,
    title: 'Plataforma E-Commerce',
    description: 'Plataforma e-commerce con integración de pagos y gestión de inventario. Incluye panel de administración y dashboard de analytics.',
    technologies: ['Next.js', 'Stripe', 'PostgreSQL'],
    image: '/api/placeholder/400/300',
    link: 'https://example.com',
    github: 'https://github.com/example',
  },
  {
    id: 4,
    title: 'Dashboard Analytics',
    description: 'Dashboard interactivo para visualización de datos con gráficos en tiempo real. Incluye filtros avanzados y exportación de reportes.',
    technologies: ['React', 'TypeScript', 'Node.js'],
    image: '/api/placeholder/400/300',
    link: 'https://example.com',
    github: 'https://github.com/example',
  },
  {
    id: 5,
    title: 'App de Tareas',
    description: 'Aplicación de gestión de tareas con sincronización en tiempo real. Incluye categorías, etiquetas y recordatorios personalizados.',
    technologies: ['React', 'TypeScript', 'MongoDB'],
    image: '/api/placeholder/400/300',
    link: 'https://example.com',
    github: 'https://github.com/example',
  },
  {
    id: 6,
    title: 'Red Social',
    description: 'Plataforma social con feed personalizado, mensajería instantánea y sistema de notificaciones. Optimizada para rendimiento.',
    technologies: ['Next.js', 'React', 'PostgreSQL'],
    image: '/api/placeholder/400/300',
    link: 'https://example.com',
    github: 'https://github.com/example',
  },
  {
    id: 7,
    title: 'Blog Personal',
    description: 'Blog personal con sistema de comentarios, búsqueda avanzada y modo oscuro. Construido con tecnologías modernas.',
    technologies: ['Next.js', 'TypeScript', 'CSS3'],
    image: '/api/placeholder/400/300',
    link: 'https://example.com',
    github: 'https://github.com/example',
  },
  {
    id: 8,
    title: 'API REST',
    description: 'API REST completa con documentación Swagger, autenticación JWT y rate limiting. Incluye tests unitarios y de integración.',
    technologies: ['Node.js', 'TypeScript', 'PostgreSQL'],
    image: '/api/placeholder/400/300',
    link: 'https://example.com',
    github: 'https://github.com/example',
  },
];

